### ISSUE TITLE
incorrect encodedSpace matrixSize entries

### ISSUE THREAD

**Issue by welcheb** [ismrmrd/philips_to_ismrmrd#4]
The encodedSpace matrixSize entries are not correct. The example MATLAB output below shows the correct size [240, 84, 36] of a 3D k-space loaded with the ismrmrd MATLAB classes. The encodedSpace matrixSize entries are incorrectly set to [448, 156, 35.9996]. IsmrmrdPhilips.xsl needs to be corrected.

> > %% true size of 3D k-space
> > nkx = meas.head.number_of_samples(1);
> > nky = range(meas.head.idx.kspace_encode_step_1(:)) + 1;
> > nkz = range(meas.head.idx.kspace_encode_step_2(:)) + 1;
> > nkx

nkx =

```
240
```

> > nky

nky =

```
 84
```

> > nkz

nkz =

```
 36
```

> > %% incorrect encodeSpace sizes
> > hdr.encoding.encodedSpace.matrixSize.x

ans =

   448

> > hdr.encoding.encodedSpace.matrixSize.y

ans =

   156

> > hdr.encoding.encodedSpace.matrixSize.z

ans =

   35.9996

**Comment by frankong** [comment]
This also happens to my dataset. The matrixSize calculated from IsmrmrdPhilips.xsl is incorrect.
